language: php

addons:
  apt:
    packages:
    - libgpgme11-dev

php:
  - 5.6

env:
  - DB=mysql

services:
  - memcached

matrix:
  fast_finish: true

before_script:
  - if [ $DB = 'mysql' ]; then sudo apt-get -y install mysql-server; fi
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE passbolt_test;'; fi"
  - chmod -R 777 ./app/tmp
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.3" ]] ; then pecl install timezonedb ; fi
  - pecl install gnupg
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
  - set +H
  - chmod -R 777 app/tmp
  - echo "<?php
    class DATABASE_CONFIG {
      public \$test = array(
        'datasource' => 'Database/Mysql',
        'database' => 'passbolt_test',
        'host' => '127.0.0.1',
        'login' => 'travis',
        'persistent' => false,
      );
    }" > app/Config/database.php
  - cp app/Config/core.php.default app/Config/core.php
  - cp app/Config/app.php.default app/Config/app.php
  - cp app/Config/email.php.default app/Config/email.php
  - sed -i "s/('debug',\s0)/('debug', 1)/" ./app/Config/core.php
  - head ./app/Config/core.php -n 42 | tail -1
  - echo `whoami`
script:
  - ./app/Console/cake install --data=unittests --no-admin
  - ./app/Console/cake test app All --stderr

notifications:
  email: false
