language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - DB=mysql

services:
  - memcached

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: PHPCS=1

before_script:
  - if [ $DB = 'mysql' ]; then sudo apt-get -y install mysql-server; fi
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE passbolt;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE passbolt_test;'; fi"
  - chmod -R 777 ./app/tmp
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.3" ]] ; then pecl install timezonedb ; fi
  - echo yes | pecl install gnupg
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=gnupg.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
  - set +H
  - chmod -R 777 app/tmp
  - echo "<?php
    class DATABASE_CONFIG {
      public \$test = array(
        'datasource' => 'Database/Mysql',
        'database' => 'cakephp_test',
        'host' => '0.0.0.0',
        'login' => 'travis',
        'persistent' => false,
      );
    }" > app/Config/database.php
  - cp app/Config/core.php.default app/Config/core.php
  - cp app/Config/app.php.default app/Config/app.php
  - cp app/Config/email.php.default app/Config/email.php
  - RUN sed -i 's/\('debug', 0\)/('debug', 1\)/' app/Config/core.php \
script:
  - sh -c "if [ '$PHPCS' != '1' ]; then ./app/Console/cake test app All --stderr --stderr; fi"

notifications:
  email: false
