language: php

addons:
  apt:
    packages:
    - libgpgme11-dev
    - php5-memcached
    - php5-json
    - php5-cli
    - php5-common
    - php5-curl
    - php5-dev
    - php5-gd
    - php5-mcrypt
    - php5-mysql
    - php5-xdebug
    - php5-xsl
    - php5-intl
    - gnupg2

php:
  - 5.6

env:
  - DB=mysql

services:
  - memcached

matrix:
  fast_finish: true

before_script:
  - if [ $DB = 'mysql' ]; then sudo apt-get -y install mysql-server; fi
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE passbolt;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE passbolt_test;'; fi"
  - chmod -R 777 ./app/tmp
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.3" ]] ; then pecl install timezonedb ; fi
  - echo yes | pecl install gnupg
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
  - set +H
  - chmod -R 777 app/tmp
  - echo "<?php
    class DATABASE_CONFIG {
      public \$default = array(
        'datasource' => 'Database/Mysql',
        'database' => 'passbolt',
        'host' => '127.0.0.1',
        'login' => 'travis',
        'password' => '',
        'persistent' => false,
      );
      public \$test = array(
        'datasource' => 'Database/Mysql',
        'database' => 'passbolt_test',
        'host' => '127.0.0.1',
        'login' => 'travis',
        'password' => '',
        'persistent' => false,
      );
    }" > app/Config/database.php
  - cp app/Config/core.php.default app/Config/core.php
  - cp app/Config/app.php.default app/Config/app.php
  - cp app/Config/email.php.default app/Config/email.php
  - sed -i "s/('debug',\s0)/('debug', 1)/" ./app/Config/core.php
  - sed -i "s/DYhG93b0qyJfIxfs2guVoUubWwvniR2G0FgaC9mi/DYhG93b0qyJfIxfs2guVoUubWwvniR2G0FgbC9mi/" ./app/Config/core.php
  - sed -i "s/76859309657453542496749683645/76859309357453542496749683645/" ./app/Config/core.php
  - sed -i "s/\/home\/www-data\/.gnupg/\/home\/travis\/.gnupg/" ./app/Config/app.php
  - gpg --allow-secret-key-import --import ./app/Config/gpg/unsecure_private.key
  - chown travis /home/travis/.gnupg
  - chmod -R 0777 /home/travis/.gnupg
script:
  - ./app/Console/cake install --data=unittests --no-admin
  - ./app/Console/cake test app All --stderr

notifications:
  email: false
